package com.tian.sakura.cdd.db.dao.task;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.db.domain.task.TaskCoupon;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskCouponMapper extends AbstractSingleMapper<TaskCoupon, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_task_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_task_coupon
     *
     * @mbg.generated
     */
    int insert(TaskCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_task_coupon
     *
     * @mbg.generated
     */
    int insertSelective(TaskCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_task_coupon
     *
     * @mbg.generated
     */
    TaskCoupon selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_task_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_task_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskCoupon record);
}