package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class TConMenu extends BaseEntity<String> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.COMPONENT
     *
     * @mbggenerated
     */
    private String component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.PATH
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.ICON_CLS
     *
     * @mbggenerated
     */
    private String iconCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.EYEABLE
     *
     * @mbggenerated
     */
    private Boolean eyeable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.KEEP_ALIVE
     *
     * @mbggenerated
     */
    private Boolean keepAlive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.PARENT_ID
     *
     * @mbggenerated
     */
    private String parentId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU.ORDER_NO
     *
     * @mbggenerated
     */
    private Short orderNo;
    
    
    private List<TConMenu> children = new ArrayList<>();
    
    private List<TConPermission> permissionList = new ArrayList<>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.NAME
     *
     * @return the value of T_CON_MENU.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.NAME
     *
     * @param name the value for T_CON_MENU.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.TITLE
     *
     * @return the value of T_CON_MENU.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.TITLE
     *
     * @param title the value for T_CON_MENU.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.COMPONENT
     *
     * @return the value of T_CON_MENU.COMPONENT
     *
     * @mbggenerated
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.COMPONENT
     *
     * @param component the value for T_CON_MENU.COMPONENT
     *
     * @mbggenerated
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.PATH
     *
     * @return the value of T_CON_MENU.PATH
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.PATH
     *
     * @param path the value for T_CON_MENU.PATH
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.ICON_CLS
     *
     * @return the value of T_CON_MENU.ICON_CLS
     *
     * @mbggenerated
     */
    public String getIconCls() {
        return iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.ICON_CLS
     *
     * @param iconCls the value for T_CON_MENU.ICON_CLS
     *
     * @mbggenerated
     */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.EYEABLE
     *
     * @return the value of T_CON_MENU.EYEABLE
     *
     * @mbggenerated
     */
    public Boolean getEyeable() {
        return eyeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.EYEABLE
     *
     * @param eyeable the value for T_CON_MENU.EYEABLE
     *
     * @mbggenerated
     */
    public void setEyeable(Boolean eyeable) {
        this.eyeable = eyeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.KEEP_ALIVE
     *
     * @return the value of T_CON_MENU.KEEP_ALIVE
     *
     * @mbggenerated
     */
    public Boolean getKeepAlive() {
        return keepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.KEEP_ALIVE
     *
     * @param keepAlive the value for T_CON_MENU.KEEP_ALIVE
     *
     * @mbggenerated
     */
    public void setKeepAlive(Boolean keepAlive) {
        this.keepAlive = keepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.PARENT_ID
     *
     * @return the value of T_CON_MENU.PARENT_ID
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.PARENT_ID
     *
     * @param parentId the value for T_CON_MENU.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU.ORDER_NO
     *
     * @return the value of T_CON_MENU.ORDER_NO
     *
     * @mbggenerated
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU.ORDER_NO
     *
     * @param orderNo the value for T_CON_MENU.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }
    

    public List<TConMenu> getChildren() {
        return children;
    }

    public void setChildren(List<TConMenu> children) {
        this.children = children;
    }

    public void addChildMenu(TConMenu menu) {
        if (this.children == null) {
            this.children = new ArrayList<>();
        }
        this.children.add(menu);

        Collections.sort(children, new Comparator<TConMenu>() {
            @Override
            public int compare(TConMenu o1, TConMenu o2) {
                if (o1.getOrderNo() == null) return -1;
                if (o2.getOrderNo() == null) return -1;
                return o1.getOrderNo() - o2.getOrderNo();
            }
        });
    }

    public List<TConPermission> getPermissionList() {
        return permissionList;
    }

    public void setPermissionList(List<TConPermission> permissionList) {
        this.permissionList = permissionList;
    }
}