package com.tian.sakura.cdd.db.domain.task;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_share
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserShare extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_share.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_share.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   对应任务明细表的主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_share.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     * Database Column Remarks:
     *   上级分享id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_share.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * Database Column Remarks:
     *   分享状态 0-待分享；1-分享成功；2-分享失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_share.share_status
     *
     * @mbg.generated
     */
    private Integer shareStatus;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_share.remark
     *
     * @mbg.generated
     */
    private String remark;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_share.user_id
     *
     * @return the value of s_user_share.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_share.user_id
     *
     * @param userId the value for s_user_share.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_share.product_id
     *
     * @return the value of s_user_share.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_share.product_id
     *
     * @param productId the value for s_user_share.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_share.task_id
     *
     * @return the value of s_user_share.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_share.task_id
     *
     * @param taskId the value for s_user_share.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_share.parent_id
     *
     * @return the value of s_user_share.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_share.parent_id
     *
     * @param parentId the value for s_user_share.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_share.share_status
     *
     * @return the value of s_user_share.share_status
     *
     * @mbg.generated
     */
    public Integer getShareStatus() {
        return shareStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_share.share_status
     *
     * @param shareStatus the value for s_user_share.share_status
     *
     * @mbg.generated
     */
    public void setShareStatus(Integer shareStatus) {
        this.shareStatus = shareStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_share.remark
     *
     * @return the value of s_user_share.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_share.remark
     *
     * @param remark the value for s_user_share.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

}