package com.tian.sakura.cdd.db.domain.log;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_amount_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class UserAmountLog extends BaseEntity<String> {

    private String id;


    private String userId;


    private Integer changeType;


    private BigDecimal changeAmount;


    private Date changeTime;


    private String remark;


    private Integer acctStatus;


    private String relationId;

    private BigDecimal oldAmount;

    //用户姓名
    private String nickName;
}