package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;

public class TConResource extends BaseEntity<String> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_RESOURCE.RESOURCE_NAME
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_RESOURCE.RESOURCE_URL
     *
     * @mbggenerated
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_RESOURCE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_RESOURCE.RESOURCE_NAME
     *
     * @return the value of T_CON_RESOURCE.RESOURCE_NAME
     *
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_RESOURCE.RESOURCE_NAME
     *
     * @param resourceName the value for T_CON_RESOURCE.RESOURCE_NAME
     *
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_RESOURCE.RESOURCE_URL
     *
     * @return the value of T_CON_RESOURCE.RESOURCE_URL
     *
     * @mbggenerated
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_RESOURCE.RESOURCE_URL
     *
     * @param resourceUrl the value for T_CON_RESOURCE.RESOURCE_URL
     *
     * @mbggenerated
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_RESOURCE.REMARK
     *
     * @return the value of T_CON_RESOURCE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_RESOURCE.REMARK
     *
     * @param remark the value for T_CON_RESOURCE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

}