package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_task
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class UserTask extends BaseEntity<String> {


    /**
     * Database Column Remarks:
     * 用户id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_task.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     * 商品ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_task.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     * 状态 1 已支付 2 未支付 3 锁定
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_task.pay_status
     *
     * @mbg.generated
     */
    private Integer payStatus;

    /**
     * Database Column Remarks:
     * 支付金额
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_task.pay_amount
     *
     * @mbg.generated
     */
    private BigDecimal payAmount;

    /**
     * Database Column Remarks:
     * 支付时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_task.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    private String remark;

    private Integer taskNumber;
    private String orderSn;
    private String userCouponId;

    /**
     * Database Column Remarks:
     * 0-APP,1-微信公众号,2-小程序
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_task.channel
     *
     * @mbg.generated
     */
    private Integer channel;

    private String nickName;

    private String productName;
}