package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_level
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class UserLevel extends BaseEntity<String> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_level.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     * 0：新人 1：见习猎人 2：初级猎人 3：中级猎人 4：高级猎人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_level.level_type
     *
     * @mbg.generated
     */
    private Integer levelType;

    /**
     * Database Column Remarks:
     * 等级名称 初级猎人 高级猎人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_level.level_name
     *
     * @mbg.generated
     */
    private String levelName;

    /**
     * Database Column Remarks:
     * 达标单数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_level.min_number
     *
     * @mbg.generated
     */
    private Integer minNumber;

    /**
     * Database Column Remarks:
     * 最大单数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_level.max_number
     *
     * @mbg.generated
     */
    private Integer maxNumber;

    /**
     * Database Column Remarks:
     * 最大购买任务线数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_level.buy_number
     *
     * @mbg.generated
     */
    private Integer buyNumber;

    /**
     * Database Column Remarks:
     * 最多并行商品数量
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_level.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;
}