package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_follow
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserFollow extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_follow.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_follow.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   任务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_follow.task_order_id
     *
     * @mbg.generated
     */
    private String taskOrderId;

    /**
     * Database Column Remarks:
     *   关注类别：（0： 关注商品  1：关注任务）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_follow.follow_type
     *
     * @mbg.generated
     */
    private Integer followType;

    /**
     * Database Column Remarks:
     *   关注状态（0：未关注或取消关注 1：已关注）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_follow.status
     *
     * @mbg.generated
     */
    private Integer followStatus;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_follow.user_id
     *
     * @return the value of s_user_follow.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_follow.user_id
     *
     * @param userId the value for s_user_follow.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_follow.product_id
     *
     * @return the value of s_user_follow.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_follow.product_id
     *
     * @param productId the value for s_user_follow.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_follow.task_order_id
     *
     * @return the value of s_user_follow.task_order_id
     *
     * @mbg.generated
     */
    public String getTaskOrderId() {
        return taskOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_follow.task_order_id
     *
     * @param taskOrderId the value for s_user_follow.task_order_id
     *
     * @mbg.generated
     */
    public void setTaskOrderId(String taskOrderId) {
        this.taskOrderId = taskOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_follow.follow_type
     *
     * @return the value of s_user_follow.follow_type
     *
     * @mbg.generated
     */
    public Integer getFollowType() {
        return followType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_follow.follow_type
     *
     * @param followType the value for s_user_follow.follow_type
     *
     * @mbg.generated
     */
    public void setFollowType(Integer followType) {
        this.followType = followType;
    }

    public Integer getFollowStatus() {
        return followStatus;
    }

    public void setFollowStatus(Integer followStatus) {
        this.followStatus = followStatus;
    }
}