package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_address
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserAddress extends BaseEntity<String> {

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.true_name
     *
     * @mbg.generated
     */
    private String trueName;

    /**
     * Database Column Remarks:
     *   省级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.province_id
     *
     * @mbg.generated
     */
    private Integer provinceId;

    /**
     * Database Column Remarks:
     *   省级名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.province_name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     * Database Column Remarks:
     *   市级ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.city_id
     *
     * @mbg.generated
     */
    private Integer cityId;

    /**
     * Database Column Remarks:
     *   市级名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     * Database Column Remarks:
     *   地区ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     * Database Column Remarks:
     *   区级名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     * Database Column Remarks:
     *   地区内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.area_info
     *
     * @mbg.generated
     */
    private String areaInfo;

    /**
     * Database Column Remarks:
     *   座机电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.tel_phone
     *
     * @mbg.generated
     */
    private String telPhone;

    /**
     * Database Column Remarks:
     *   手机电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.mob_phone
     *
     * @mbg.generated
     */
    private String mobPhone;

    /**
     * Database Column Remarks:
     *   1默认收货地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.is_default
     *
     * @mbg.generated
     */
    private String isDefault;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_address.zip_code
     *
     * @mbg.generated
     */
    private Integer zipCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.user_id
     *
     * @return the value of s_user_address.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.user_id
     *
     * @param userId the value for s_user_address.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.true_name
     *
     * @return the value of s_user_address.true_name
     *
     * @mbg.generated
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.true_name
     *
     * @param trueName the value for s_user_address.true_name
     *
     * @mbg.generated
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.province_id
     *
     * @return the value of s_user_address.province_id
     *
     * @mbg.generated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.province_id
     *
     * @param provinceId the value for s_user_address.province_id
     *
     * @mbg.generated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.province_name
     *
     * @return the value of s_user_address.province_name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.province_name
     *
     * @param provinceName the value for s_user_address.province_name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.city_id
     *
     * @return the value of s_user_address.city_id
     *
     * @mbg.generated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.city_id
     *
     * @param cityId the value for s_user_address.city_id
     *
     * @mbg.generated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.city_name
     *
     * @return the value of s_user_address.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.city_name
     *
     * @param cityName the value for s_user_address.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.area_id
     *
     * @return the value of s_user_address.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.area_id
     *
     * @param areaId the value for s_user_address.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.area_name
     *
     * @return the value of s_user_address.area_name
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.area_name
     *
     * @param areaName the value for s_user_address.area_name
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.area_info
     *
     * @return the value of s_user_address.area_info
     *
     * @mbg.generated
     */
    public String getAreaInfo() {
        return areaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.area_info
     *
     * @param areaInfo the value for s_user_address.area_info
     *
     * @mbg.generated
     */
    public void setAreaInfo(String areaInfo) {
        this.areaInfo = areaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.tel_phone
     *
     * @return the value of s_user_address.tel_phone
     *
     * @mbg.generated
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.tel_phone
     *
     * @param telPhone the value for s_user_address.tel_phone
     *
     * @mbg.generated
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.mob_phone
     *
     * @return the value of s_user_address.mob_phone
     *
     * @mbg.generated
     */
    public String getMobPhone() {
        return mobPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.mob_phone
     *
     * @param mobPhone the value for s_user_address.mob_phone
     *
     * @mbg.generated
     */
    public void setMobPhone(String mobPhone) {
        this.mobPhone = mobPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.is_default
     *
     * @return the value of s_user_address.is_default
     *
     * @mbg.generated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.is_default
     *
     * @param isDefault the value for s_user_address.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_address.zip_code
     *
     * @return the value of s_user_address.zip_code
     *
     * @mbg.generated
     */
    public Integer getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_address.zip_code
     *
     * @param zipCode the value for s_user_address.zip_code
     *
     * @mbg.generated
     */
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

}