package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import com.tian.sakura.cdd.db.domain.shop.ShopCoupon;
import com.tian.sakura.cdd.db.domain.task.TaskCoupon;
import lombok.Data;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_coupon
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class UserCoupon extends BaseEntity<String> {


    /**
     * Database Column Remarks:
     * 用户id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_coupon.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     * 券id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_coupon.coupon_id
     *
     * @mbg.generated
     */
    private String couponId;

    /**
     * Database Column Remarks:
     * 商品ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_coupon.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     * 券类型 0-任务金 1-商铺券
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_coupon.coupon_type
     *
     * @mbg.generated
     */
    private Integer couponType;

    /**
     * Database Column Remarks:
     * 0-未使用 ；1-已使用；2-过期
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_coupon.coupon_status
     *
     * @mbg.generated
     */
    private Integer couponStatus;

    private String productName;

    private ShopCoupon shopCoupon;

}