package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_wechat
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserWechat extends BaseEntity<String> {

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   用户手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.user_img
     *
     * @mbg.generated
     */
    private String userImg;

    /**
     * Database Column Remarks:
     *   微信openId(打款时需要)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     * Database Column Remarks:
     *   微信unionid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.union_id
     *
     * @mbg.generated
     */
    private String unionId;

    /**
     * Database Column Remarks:
     *   上级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * Database Column Remarks:
     *   邀请码（随机生成 大写字母+数字 4位 ）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.invite_code
     *
     * @mbg.generated
     */
    private String inviteCode;

    /**
     * Database Column Remarks:
     *   0-APP,1-微信公众号,2-小程序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.channel
     *
     * @mbg.generated
     */
    private Integer channel;

    /**
     * Database Column Remarks:
     *   最后一次登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_wechat.last_login
     *
     * @mbg.generated
     */
    private Date lastLogin;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.nick_name
     *
     * @return the value of s_user_wechat.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.nick_name
     *
     * @param nickName the value for s_user_wechat.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.user_phone
     *
     * @return the value of s_user_wechat.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.user_phone
     *
     * @param userPhone the value for s_user_wechat.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.user_img
     *
     * @return the value of s_user_wechat.user_img
     *
     * @mbg.generated
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.user_img
     *
     * @param userImg the value for s_user_wechat.user_img
     *
     * @mbg.generated
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.open_id
     *
     * @return the value of s_user_wechat.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.open_id
     *
     * @param openId the value for s_user_wechat.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.union_id
     *
     * @return the value of s_user_wechat.union_id
     *
     * @mbg.generated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.union_id
     *
     * @param unionId the value for s_user_wechat.union_id
     *
     * @mbg.generated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.parent_id
     *
     * @return the value of s_user_wechat.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.parent_id
     *
     * @param parentId the value for s_user_wechat.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.invite_code
     *
     * @return the value of s_user_wechat.invite_code
     *
     * @mbg.generated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.invite_code
     *
     * @param inviteCode the value for s_user_wechat.invite_code
     *
     * @mbg.generated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.channel
     *
     * @return the value of s_user_wechat.channel
     *
     * @mbg.generated
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.channel
     *
     * @param channel the value for s_user_wechat.channel
     *
     * @mbg.generated
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_wechat.last_login
     *
     * @return the value of s_user_wechat.last_login
     *
     * @mbg.generated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_wechat.last_login
     *
     * @param lastLogin the value for s_user_wechat.last_login
     *
     * @mbg.generated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }


}