package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_login_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserLoginLog extends BaseEntity<String> {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_login_log.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_login_log.union_id
     *
     * @mbg.generated
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_login_log.login_time
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_login_log.login_device_id
     *
     * @mbg.generated
     */
    private String loginDeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_login_log.login_ip
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_login_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_login_log.user_id
     *
     * @return the value of s_user_login_log.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_login_log.user_id
     *
     * @param userId the value for s_user_login_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_login_log.union_id
     *
     * @return the value of s_user_login_log.union_id
     *
     * @mbg.generated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_login_log.union_id
     *
     * @param unionId the value for s_user_login_log.union_id
     *
     * @mbg.generated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_login_log.login_time
     *
     * @return the value of s_user_login_log.login_time
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_login_log.login_time
     *
     * @param loginTime the value for s_user_login_log.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_login_log.login_device_id
     *
     * @return the value of s_user_login_log.login_device_id
     *
     * @mbg.generated
     */
    public String getLoginDeviceId() {
        return loginDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_login_log.login_device_id
     *
     * @param loginDeviceId the value for s_user_login_log.login_device_id
     *
     * @mbg.generated
     */
    public void setLoginDeviceId(String loginDeviceId) {
        this.loginDeviceId = loginDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_login_log.login_ip
     *
     * @return the value of s_user_login_log.login_ip
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_login_log.login_ip
     *
     * @param loginIp the value for s_user_login_log.login_ip
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_login_log.remark
     *
     * @return the value of s_user_login_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_login_log.remark
     *
     * @param remark the value for s_user_login_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}