package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_sign_max
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserSignMax extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     *   用户标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign_max.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   连续签到次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign_max.sign_max_cnt
     *
     * @mbg.generated
     */
    private Integer signMaxCnt;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign_max.user_id
     *
     * @return the value of s_user_sign_max.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign_max.user_id
     *
     * @param userId the value for s_user_sign_max.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
        setId(userId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign_max.sign_max_cnt
     *
     * @return the value of s_user_sign_max.sign_max_cnt
     *
     * @mbg.generated
     */
    public Integer getSignMaxCnt() {
        return signMaxCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign_max.sign_max_cnt
     *
     * @param signMaxCnt the value for s_user_sign_max.sign_max_cnt
     *
     * @mbg.generated
     */
    public void setSignMaxCnt(Integer signMaxCnt) {
        this.signMaxCnt = signMaxCnt;
    }

}