package com.tian.sakura.cdd.db.domain.base;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sms_verify
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SmsVerify extends BaseEntity<String> {

    /**
     * Database Column Remarks:
     *   短信场景 001-注册；002-登录;003-找回密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_verify.sms_type
     *
     * @mbg.generated
     */
    private String smsType;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_verify.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   短信验证码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_verify.sms_code
     *
     * @mbg.generated
     */
    private String smsCode;

    /**
     * Database Column Remarks:
     *   是否使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_verify.used
     *
     * @mbg.generated
     */
    private String used;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_verify.sms_type
     *
     * @return the value of t_sms_verify.sms_type
     *
     * @mbg.generated
     */
    public String getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_verify.sms_type
     *
     * @param smsType the value for t_sms_verify.sms_type
     *
     * @mbg.generated
     */
    public void setSmsType(String smsType) {
        this.smsType = smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_verify.mobile
     *
     * @return the value of t_sms_verify.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_verify.mobile
     *
     * @param mobile the value for t_sms_verify.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_verify.sms_code
     *
     * @return the value of t_sms_verify.sms_code
     *
     * @mbg.generated
     */
    public String getSmsCode() {
        return smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_verify.sms_code
     *
     * @param smsCode the value for t_sms_verify.sms_code
     *
     * @mbg.generated
     */
    public void setSmsCode(String smsCode) {
        this.smsCode = smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_verify.used
     *
     * @return the value of t_sms_verify.used
     *
     * @mbg.generated
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_verify.used
     *
     * @param used the value for t_sms_verify.used
     *
     * @mbg.generated
     */
    public void setUsed(String used) {
        this.used = used;
    }

}