package com.tian.sakura.cdd.db.dao.params;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.db.domain.params.Params;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ParamsMapper extends AbstractSingleMapper<Params, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_params
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_params
     *
     * @mbg.generated
     */
    int insert(Params record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_params
     *
     * @mbg.generated
     */
    int insertSelective(Params record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_params
     *
     * @mbg.generated
     */
    Params selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_params
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Params record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_params
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Params record);

    String getValueByKey(@Param("key") String key);

    int updateValueByKey(@Param("key") String key, @Param("value") String value);
}