package com.tian.sakura.cdd.db.domain.productImg;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_product_img
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductImg extends BaseEntity<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_img.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_img.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   图片url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_img.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * Database Column Remarks:
     *   店铺id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_img.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_img.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_img.create_oper
     *
     * @mbg.generated
     */
    private String createOper;

    
    private Integer imgType;

    public Integer getImgType() {
		return imgType;
	}

	public void setImgType(Integer imgType) {
		this.imgType = imgType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_img.id
     *
     * @return the value of s_product_img.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_img.id
     *
     * @param id the value for s_product_img.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_img.product_id
     *
     * @return the value of s_product_img.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_img.product_id
     *
     * @param productId the value for s_product_img.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_img.img_url
     *
     * @return the value of s_product_img.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_img.img_url
     *
     * @param imgUrl the value for s_product_img.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_img.shop_id
     *
     * @return the value of s_product_img.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_img.shop_id
     *
     * @param shopId the value for s_product_img.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_img.create_time
     *
     * @return the value of s_product_img.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_img.create_time
     *
     * @param createTime the value for s_product_img.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_img.create_oper
     *
     * @return the value of s_product_img.create_oper
     *
     * @mbg.generated
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_img.create_oper
     *
     * @param createOper the value for s_product_img.create_oper
     *
     * @mbg.generated
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper;
    }
}