package com.tian.sakura.cdd.db.domain.cust;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_cust
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Customer extends BaseEntity<Long> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.CUST_NO
     *
     * @mbg.generated
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.NICK_NAME
     *
     * @mbg.generated
     */
    private String nickName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.CUST_NO
     *
     * @return the value of t_cust.CUST_NO
     *
     * @mbg.generated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.CUST_NO
     *
     * @param custNo the value for t_cust.CUST_NO
     *
     * @mbg.generated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.MOBILE
     *
     * @return the value of t_cust.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.MOBILE
     *
     * @param mobile the value for t_cust.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.NICK_NAME
     *
     * @return the value of t_cust.NICK_NAME
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.NICK_NAME
     *
     * @param nickName the value for t_cust.NICK_NAME
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

}