package com.tian.sakura.cdd.db.domain.banner;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_banner
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Banner extends BaseEntity<String> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     * banner名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.banner_name
     *
     * @mbg.generated
     */
    private String bannerName;

    /**
     * Database Column Remarks:
     * 0-APP引导页,1-首页轮播图
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.banner_type
     *
     * @mbg.generated
     */
    private Integer bannerType;

    /**
     * Database Column Remarks:
     * banner图片url
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.banner_url
     *
     * @mbg.generated
     */
    private String bannerUrl;

    /**
     * Database Column Remarks:
     * banner跳转url
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.jump_url
     *
     * @mbg.generated
     */
    private String jumpUrl;

    /**
     * Database Column Remarks:
     * 显示顺序
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.s_order
     *
     * @mbg.generated
     */
    private Integer sOrder;

    /**
     * Database Column Remarks:
     * 状态 0-创建 1-发布 2-下架 3-删除
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.banner_status
     *
     * @mbg.generated
     */
    private Integer bannerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_banner.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;
}