package com.tian.sakura.cdd.db.domain.params;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_params
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Params extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     * 主键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_params.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     * 代码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_params.p_key
     *
     * @mbg.generated
     */
    private String pKey;

    /**
     * Database Column Remarks:
     * 值
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_params.p_value
     *
     * @mbg.generated
     */
    private String pValue;

    /**
     * Database Column Remarks:
     * 备注
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_params.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_params.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_params.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;
}