package com.tian.sakura.cdd.db.domain.area;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;

import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_area
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Area extends BaseEntity<Integer> {
    /**
     * Database Column Remarks:
     *   索引ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   地区名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     * Database Column Remarks:
     *   地区父ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_parent_id
     *
     * @mbg.generated
     */
    private Integer areaParentId;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_sort
     *
     * @mbg.generated
     */
    private Integer areaSort;

    /**
     * Database Column Remarks:
     *   地区深度，从1开始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_deep
     *
     * @mbg.generated
     */
    private Integer areaDeep;

    /**
     * Database Column Remarks:
     *   是否删除0:未删除;1:已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    private List<Area> childList;
}