package com.tian.sakura.cdd.db.domain.product;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_product_spec_value
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductSpecValue extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     *   规格值表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   商品分类id,s_product_type表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.product_type_id
     *
     * @mbg.generated
     */
    private String productTypeId;

    /**
     * Database Column Remarks:
     *   规格值名称（颜色）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.value_type
     *
     * @mbg.generated
     */
    private String valueType;

    /**
     * Database Column Remarks:
     *   规格值名称（黑色）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.value_name
     *
     * @mbg.generated
     */
    private String valueName;

    /**
     * Database Column Remarks:
     *   规格图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.value_image
     *
     * @mbg.generated
     */
    private String valueImage;

    /**
     * Database Column Remarks:
     *   规格值排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.value_sort
     *
     * @mbg.generated
     */
    private Integer valueSort;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     * Database Column Remarks:
     *   update_user
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_spec_value.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;

    public String getProductTypeName() {
        return productTypeName;
    }

    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    private String productTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.id
     *
     * @return the value of s_product_spec_value.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.id
     *
     * @param id the value for s_product_spec_value.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.product_type_id
     *
     * @return the value of s_product_spec_value.product_type_id
     *
     * @mbg.generated
     */
    public String getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.product_type_id
     *
     * @param productTypeId the value for s_product_spec_value.product_type_id
     *
     * @mbg.generated
     */
    public void setProductTypeId(String productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.value_type
     *
     * @return the value of s_product_spec_value.value_type
     *
     * @mbg.generated
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.value_type
     *
     * @param valueType the value for s_product_spec_value.value_type
     *
     * @mbg.generated
     */
    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.value_name
     *
     * @return the value of s_product_spec_value.value_name
     *
     * @mbg.generated
     */
    public String getValueName() {
        return valueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.value_name
     *
     * @param valueName the value for s_product_spec_value.value_name
     *
     * @mbg.generated
     */
    public void setValueName(String valueName) {
        this.valueName = valueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.value_image
     *
     * @return the value of s_product_spec_value.value_image
     *
     * @mbg.generated
     */
    public String getValueImage() {
        return valueImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.value_image
     *
     * @param valueImage the value for s_product_spec_value.value_image
     *
     * @mbg.generated
     */
    public void setValueImage(String valueImage) {
        this.valueImage = valueImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.value_sort
     *
     * @return the value of s_product_spec_value.value_sort
     *
     * @mbg.generated
     */
    public Integer getValueSort() {
        return valueSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.value_sort
     *
     * @param valueSort the value for s_product_spec_value.value_sort
     *
     * @mbg.generated
     */
    public void setValueSort(Integer valueSort) {
        this.valueSort = valueSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.create_time
     *
     * @return the value of s_product_spec_value.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.create_time
     *
     * @param createTime the value for s_product_spec_value.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.update_time
     *
     * @return the value of s_product_spec_value.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.update_time
     *
     * @param updateTime the value for s_product_spec_value.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.create_user
     *
     * @return the value of s_product_spec_value.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.create_user
     *
     * @param createUser the value for s_product_spec_value.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_spec_value.update_user
     *
     * @return the value of s_product_spec_value.update_user
     *
     * @mbg.generated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_spec_value.update_user
     *
     * @param updateUser the value for s_product_spec_value.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}