package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table T_CON_ROLE_MENU_PERM
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TConRoleMenuPerm extends BaseEntity<String> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_ROLE_MENU_PERM.ROLE_ID
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_ROLE_MENU_PERM.MENU_ID
     *
     * @mbg.generated
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_ROLE_MENU_PERM.PERM_ID
     *
     * @mbg.generated
     */
    private String permId;

    public TConRoleMenuPerm() {

    }

    public TConRoleMenuPerm(String roleId, String menuId, String permId) {
        this.roleId = roleId;
        this.menuId = menuId;
        this.permId = permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_ROLE_MENU_PERM.ROLE_ID
     *
     * @return the value of T_CON_ROLE_MENU_PERM.ROLE_ID
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_ROLE_MENU_PERM.ROLE_ID
     *
     * @param roleId the value for T_CON_ROLE_MENU_PERM.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_ROLE_MENU_PERM.MENU_ID
     *
     * @return the value of T_CON_ROLE_MENU_PERM.MENU_ID
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_ROLE_MENU_PERM.MENU_ID
     *
     * @param menuId the value for T_CON_ROLE_MENU_PERM.MENU_ID
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_ROLE_MENU_PERM.PERM_ID
     *
     * @return the value of T_CON_ROLE_MENU_PERM.PERM_ID
     *
     * @mbg.generated
     */
    public String getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_ROLE_MENU_PERM.PERM_ID
     *
     * @param permId the value for T_CON_ROLE_MENU_PERM.PERM_ID
     *
     * @mbg.generated
     */
    public void setPermId(String permId) {
        this.permId = permId;
    }
}