package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;

public class TConUserRole extends BaseEntity<String> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_USER_ROLE.USER_ID
     *
     * @return the value of T_CON_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_USER_ROLE.USER_ID
     *
     * @param userId the value for T_CON_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_USER_ROLE.ROLE_ID
     *
     * @return the value of T_CON_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for T_CON_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}