package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;

public class TConUser extends BaseEntity<String> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_USER.USER_NO
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_USER.USER_PASSWD
     *
     * @mbggenerated
     */
    private String userPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_USER.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_USER.USER_NO
     *
     * @return the value of T_CON_USER.USER_NO
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_USER.USER_NO
     *
     * @param userNo the value for T_CON_USER.USER_NO
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_USER.USER_PASSWD
     *
     * @return the value of T_CON_USER.USER_PASSWD
     *
     * @mbggenerated
     */
    public String getUserPasswd() {
        return userPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_USER.USER_PASSWD
     *
     * @param userPasswd the value for T_CON_USER.USER_PASSWD
     *
     * @mbggenerated
     */
    public void setUserPasswd(String userPasswd) {
        this.userPasswd = userPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_USER.USER_NAME
     *
     * @return the value of T_CON_USER.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_USER.USER_NAME
     *
     * @param userName the value for T_CON_USER.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

}