package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;

public class TConMenuRole extends BaseEntity<String>{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_MENU_ROLE.MENU_ID
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU_ROLE.ROLE_ID
     *
     * @return the value of T_CON_MENU_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU_ROLE.ROLE_ID
     *
     * @param roleId the value for T_CON_MENU_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_MENU_ROLE.MENU_ID
     *
     * @return the value of T_CON_MENU_ROLE.MENU_ID
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_MENU_ROLE.MENU_ID
     *
     * @param menuId the value for T_CON_MENU_ROLE.MENU_ID
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}