package com.tian.sakura.cdd.db.dao.product;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.db.domain.product.ProductSpec;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProductSpecMapper extends AbstractSingleMapper<ProductSpec, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_product_spec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_product_spec
     *
     * @mbg.generated
     */
    int insert(ProductSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_product_spec
     *
     * @mbg.generated
     */
    int insertSelective(ProductSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_product_spec
     *
     * @mbg.generated
     */
    ProductSpec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_product_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_product_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductSpec record);

    List<ProductSpec> listProductSpec(@Param("productId") String productId);

    int updateDeleteFlag(@Param("id") String id);

    ProductSpec selectByProductIdAndSpecValueId(@Param("productId") String productId,
                                    @Param("productSpecValueId") String productSpecValueId);


    void decreaseStock(@Param("id") Integer id, @Param("productNumber")Integer prdCount);

    void increaseStock(@Param("id")Integer id, @Param("productNumber")Integer prdCount);
}