package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_relation
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserRelation extends BaseEntity<String> {


    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_relation.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   上级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_relation.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * Database Column Remarks:
     *   关系类型 0-预备队 1-近卫军
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_relation.relation_type
     *
     * @mbg.generated
     */
    private Integer relationType;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_relation.union_id
     *
     * @mbg.generated
     */
    private String unionId;

    private String userName;
    private String nickName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_relation.user_id
     *
     * @return the value of s_user_relation.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_relation.user_id
     *
     * @param userId the value for s_user_relation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_relation.parent_id
     *
     * @return the value of s_user_relation.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_relation.parent_id
     *
     * @param parentId the value for s_user_relation.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_relation.relation_type
     *
     * @return the value of s_user_relation.relation_type
     *
     * @mbg.generated
     */
    public Integer getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_relation.relation_type
     *
     * @param relationType the value for s_user_relation.relation_type
     *
     * @mbg.generated
     */
    public void setRelationType(Integer relationType) {
        this.relationType = relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_relation.union_id
     *
     * @return the value of s_user_relation.union_id
     *
     * @mbg.generated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_relation.union_id
     *
     * @param unionId the value for s_user_relation.union_id
     *
     * @mbg.generated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
}