package com.tian.sakura.cdd.db.domain.base;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import com.tian.sakura.cdd.db.domain.product.Product;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_recommend_type
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RecommendType extends BaseEntity<String> {

    private String id;
    /**
     * Database Column Remarks:
     * 推荐title
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_recommend_type.recommend_title
     *
     * @mbg.generated
     */
    private String recommendTitle;

    /**
     * Database Column Remarks:
     * 显示顺序
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_recommend_type.s_order
     *
     * @mbg.generated
     */
    private Integer sOrder;

    /**
     * Database Column Remarks:
     * 状态 0-创建 1-发布 2-下架 3-删除
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_recommend_type.recommend_status
     *
     * @mbg.generated
     */
    private Integer recommendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_recommend_type.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_recommend_type.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;

    /**
     * Database Column Remarks:
     * 排版风格 0-推荐 1-常规
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_recommend_type.page_style
     *
     * @mbg.generated
     */
    private String pageStyle;

    private List<Product> productList;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_activity.id
     *
     * @param id the value for s_activity.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_recommend_type.recommend_title
     *
     * @return the value of s_recommend_type.recommend_title
     * @mbg.generated
     */
    public String getRecommendTitle() {
        return recommendTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_recommend_type.recommend_title
     *
     * @param recommendTitle the value for s_recommend_type.recommend_title
     * @mbg.generated
     */
    public void setRecommendTitle(String recommendTitle) {
        this.recommendTitle = recommendTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_recommend_type.s_order
     *
     * @return the value of s_recommend_type.s_order
     * @mbg.generated
     */
    public Integer getsOrder() {
        return sOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_recommend_type.s_order
     *
     * @param sOrder the value for s_recommend_type.s_order
     * @mbg.generated
     */
    public void setsOrder(Integer sOrder) {
        this.sOrder = sOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_recommend_type.recommend_status
     *
     * @return the value of s_recommend_type.recommend_status
     * @mbg.generated
     */
    public Integer getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_recommend_type.recommend_status
     *
     * @param recommendStatus the value for s_recommend_type.recommend_status
     * @mbg.generated
     */
    public void setRecommendStatus(Integer recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_recommend_type.create_user
     *
     * @return the value of s_recommend_type.create_user
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_recommend_type.create_user
     *
     * @param createUser the value for s_recommend_type.create_user
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_recommend_type.update_user
     *
     * @return the value of s_recommend_type.update_user
     * @mbg.generated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_recommend_type.update_user
     *
     * @param updateUser the value for s_recommend_type.update_user
     * @mbg.generated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_recommend_type.page_style
     *
     * @return the value of s_recommend_type.page_style
     * @mbg.generated
     */
    public String getPageStyle() {
        return pageStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_recommend_type.page_style
     *
     * @param pageStyle the value for s_recommend_type.page_style
     * @mbg.generated
     */
    public void setPageStyle(String pageStyle) {
        this.pageStyle = pageStyle;
    }

    public List<Product> getProductList() {
        return productList;
    }

    public void setProductList(List<Product> productList) {
        this.productList = productList;
    }
}