package com.tian.sakura.cdd.db.domain.shopReturn;

import java.util.Date;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_shop_return
 * 退货地址与自提地址
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopReturn extends BaseEntity<Integer>{
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_return.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商铺id(s_shop表主键)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_return.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_return.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_return.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区县
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_return.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_return.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_return.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    
    private int addressType;

    public int getAddressType() {
		return addressType;
	}

	public void setAddressType(int addressType) {
		this.addressType = addressType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_return.id
     *
     * @return the value of s_shop_return.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_return.id
     *
     * @param id the value for s_shop_return.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_return.shop_id
     *
     * @return the value of s_shop_return.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_return.shop_id
     *
     * @param shopId the value for s_shop_return.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_return.province
     *
     * @return the value of s_shop_return.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_return.province
     *
     * @param province the value for s_shop_return.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_return.city
     *
     * @return the value of s_shop_return.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_return.city
     *
     * @param city the value for s_shop_return.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_return.country
     *
     * @return the value of s_shop_return.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_return.country
     *
     * @param country the value for s_shop_return.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_return.address
     *
     * @return the value of s_shop_return.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_return.address
     *
     * @param address the value for s_shop_return.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_return.create_time
     *
     * @return the value of s_shop_return.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_return.create_time
     *
     * @param createTime the value for s_shop_return.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public Integer provinceId;
    public Integer cityId;
    public Integer countryId;

	public Integer getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getCountryId() {
		return countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}
}