package com.tian.sakura.cdd.db.domain.userBonusLog;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_bonus_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserBonusLog extends BaseEntity<String> {

    private String productId;
    private String taskLineId;
    private String userId;
    private String orderDetailId;
    private String userTaskLineId;

    private Integer bonusType;

    private BigDecimal bonusAmount;

    private String remark;

    private Integer logStatus;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_bonus_log.user_id
     *
     * @return the value of s_user_bonus_log.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_bonus_log.user_id
     *
     * @param userId the value for s_user_bonus_log.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_bonus_log.order_detail_id
     *
     * @return the value of s_user_bonus_log.order_detail_id
     * @mbg.generated
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_bonus_log.order_detail_id
     *
     * @param orderDetailId the value for s_user_bonus_log.order_detail_id
     * @mbg.generated
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_bonus_log.user_task_line_id
     *
     * @return the value of s_user_bonus_log.user_task_line_id
     * @mbg.generated
     */
    public String getUserTaskLineId() {
        return userTaskLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_bonus_log.user_task_line_id
     *
     * @param userTaskLineId the value for s_user_bonus_log.user_task_line_id
     * @mbg.generated
     */
    public void setUserTaskLineId(String userTaskLineId) {
        this.userTaskLineId = userTaskLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_bonus_log.bonus_type
     *
     * @return the value of s_user_bonus_log.bonus_type
     * @mbg.generated
     */
    public Integer getBonusType() {
        return bonusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_bonus_log.bonus_type
     *
     * @param bonusType the value for s_user_bonus_log.bonus_type
     * @mbg.generated
     */
    public void setBonusType(Integer bonusType) {
        this.bonusType = bonusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_bonus_log.bonus_amount
     *
     * @return the value of s_user_bonus_log.bonus_amount
     * @mbg.generated
     */
    public BigDecimal getBonusAmount() {
        return bonusAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_bonus_log.bonus_amount
     *
     * @param bonusAmount the value for s_user_bonus_log.bonus_amount
     * @mbg.generated
     */
    public void setBonusAmount(BigDecimal bonusAmount) {
        this.bonusAmount = bonusAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_bonus_log.remark
     *
     * @return the value of s_user_bonus_log.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_bonus_log.remark
     *
     * @param remark the value for s_user_bonus_log.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getLogStatus() {
        return logStatus;
    }

    public void setLogStatus(Integer logStatus) {
        this.logStatus = logStatus;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getTaskLineId() {
        return taskLineId;
    }

    public void setTaskLineId(String taskLineId) {
        this.taskLineId = taskLineId;
    }
}