package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_sign
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserSign extends BaseEntity<String> {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign.sign_date
     *
     * @mbg.generated
     */
    private String signDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign.sign_continue
     *
     * @mbg.generated
     */
    private Integer signContinue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign.sign_year
     *
     * @mbg.generated
     */
    private Integer signYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign.sign_month
     *
     * @mbg.generated
     */
    private Integer signMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_sign.sign_day
     *
     * @mbg.generated
     */
    private Integer signDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign.user_id
     *
     * @return the value of s_user_sign.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign.user_id
     *
     * @param userId the value for s_user_sign.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign.sign_date
     *
     * @return the value of s_user_sign.sign_date
     *
     * @mbg.generated
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign.sign_date
     *
     * @param signDate the value for s_user_sign.sign_date
     *
     * @mbg.generated
     */
    public void setSignDate(String signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign.sign_continue
     *
     * @return the value of s_user_sign.sign_continue
     *
     * @mbg.generated
     */
    public Integer getSignContinue() {
        return signContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign.sign_continue
     *
     * @param signContinue the value for s_user_sign.sign_continue
     *
     * @mbg.generated
     */
    public void setSignContinue(Integer signContinue) {
        this.signContinue = signContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign.sign_year
     *
     * @return the value of s_user_sign.sign_year
     *
     * @mbg.generated
     */
    public Integer getSignYear() {
        return signYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign.sign_year
     *
     * @param signYear the value for s_user_sign.sign_year
     *
     * @mbg.generated
     */
    public void setSignYear(Integer signYear) {
        this.signYear = signYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign.sign_month
     *
     * @return the value of s_user_sign.sign_month
     *
     * @mbg.generated
     */
    public Integer getSignMonth() {
        return signMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign.sign_month
     *
     * @param signMonth the value for s_user_sign.sign_month
     *
     * @mbg.generated
     */
    public void setSignMonth(Integer signMonth) {
        this.signMonth = signMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_sign.sign_day
     *
     * @return the value of s_user_sign.sign_day
     *
     * @mbg.generated
     */
    public Integer getSignDay() {
        return signDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_sign.sign_day
     *
     * @param signDay the value for s_user_sign.sign_day
     *
     * @mbg.generated
     */
    public void setSignDay(Integer signDay) {
        this.signDay = signDay;
    }


}