package com.tian.sakura.cdd.db.domain.shopUser;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_shop_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopUser  extends BaseEntity<Integer> {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id(s_user表主键)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   商铺id(s_shop表主键)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_user.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * Database Column Remarks:
     *   0-正常  1-注销
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_user.status
     *
     * @mbg.generated
     */
    private Integer shopStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_user.id
     *
     * @return the value of s_shop_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_user.id
     *
     * @param id the value for s_shop_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_user.user_id
     *
     * @return the value of s_shop_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_user.user_id
     *
     * @param userId the value for s_shop_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_user.shop_id
     *
     * @return the value of s_shop_user.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_user.shop_id
     *
     * @param shopId the value for s_shop_user.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_user.status
     *
     * @param status the value for s_shop_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer shopStatus) {
        this.shopStatus = shopStatus;
    }
}