package com.tian.sakura.cdd.db.dao.banner;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.db.domain.banner.Banner;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BannerMapper extends AbstractSingleMapper<Banner, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_banner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_banner
     *
     * @mbg.generated
     */
    int insert(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_banner
     *
     * @mbg.generated
     */
    int insertSelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_banner
     *
     * @mbg.generated
     */
    Banner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Banner record);

    List<Banner> listUsableBanner(@Param("bannerType") Integer bannerType);

    List<Banner> listBanner(Banner banner);

    int deleteBanner(@Param("id") String id);
}