package com.tian.sakura.cdd.db.domain.shopGroup;

import java.util.Date;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_shop_group
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopGroup extends BaseEntity<Integer>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   店铺id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_group.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * Database Column Remarks:
     *   分组名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_group.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_group.create_oper
     *
     * @mbg.generated
     */
    private String createOper;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_group.id
     *
     * @return the value of s_shop_group.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_group.id
     *
     * @param id the value for s_shop_group.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_group.shop_id
     *
     * @return the value of s_shop_group.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_group.shop_id
     *
     * @param shopId the value for s_shop_group.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_group.group_name
     *
     * @return the value of s_shop_group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_group.group_name
     *
     * @param groupName the value for s_shop_group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_group.create_time
     *
     * @return the value of s_shop_group.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_group.create_time
     *
     * @param createTime the value for s_shop_group.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_group.create_oper
     *
     * @return the value of s_shop_group.create_oper
     *
     * @mbg.generated
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_group.create_oper
     *
     * @param createOper the value for s_shop_group.create_oper
     *
     * @mbg.generated
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper;
    }
}