package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import java.util.Objects;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table T_CON_PERMISSION
 */
public class TConPermission extends BaseEntity<String>{

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_PERMISSION.PERMISSION_NO
     *
     * @mbg.generated
     */
    private String permissionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_PERMISSION.PERMISSION_NAME
     *
     * @mbg.generated
     */
    private String permissionName;

    private String aliasName;

    private boolean selected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_PERMISSION.REMARK
     *
     * @mbg.generated
     */
    private String remark;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_PERMISSION.PERMISSION_NO
     *
     * @return the value of T_CON_PERMISSION.PERMISSION_NO
     *
     * @mbg.generated
     */
    public String getPermissionNo() {
        return permissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_PERMISSION.PERMISSION_NO
     *
     * @param permissionNo the value for T_CON_PERMISSION.PERMISSION_NO
     *
     * @mbg.generated
     */
    public void setPermissionNo(String permissionNo) {
        this.permissionNo = permissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_PERMISSION.PERMISSION_NAME
     *
     * @return the value of T_CON_PERMISSION.PERMISSION_NAME
     *
     * @mbg.generated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_PERMISSION.PERMISSION_NAME
     *
     * @param permissionName the value for T_CON_PERMISSION.PERMISSION_NAME
     *
     * @mbg.generated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_PERMISSION.REMARK
     *
     * @return the value of T_CON_PERMISSION.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_PERMISSION.REMARK
     *
     * @param remark the value for T_CON_PERMISSION.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAliasName() {
        return aliasName;
    }

    public void setAliasName(String aliasName) {
        this.aliasName = aliasName;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TConPermission that = (TConPermission) o;
        return Objects.equals(getId(), that.getId());
    }

    @Override
    public int hashCode() {

        return Objects.hash(getId());
    }
}