package com.tian.sakura.cdd.db.domain.productReviewStat;

import java.util.Date;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_product_review_stat
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductReviewStat  extends BaseEntity<String>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_review_stat.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_review_stat.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   点击详情的次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_review_stat.cnt
     *
     * @mbg.generated
     */
    private Integer cnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_review_stat.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product_review_stat.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_review_stat.id
     *
     * @return the value of s_product_review_stat.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_review_stat.id
     *
     * @param id the value for s_product_review_stat.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_review_stat.product_id
     *
     * @return the value of s_product_review_stat.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_review_stat.product_id
     *
     * @param productId the value for s_product_review_stat.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_review_stat.cnt
     *
     * @return the value of s_product_review_stat.cnt
     *
     * @mbg.generated
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_review_stat.cnt
     *
     * @param cnt the value for s_product_review_stat.cnt
     *
     * @mbg.generated
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_review_stat.create_time
     *
     * @return the value of s_product_review_stat.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_review_stat.create_time
     *
     * @param createTime the value for s_product_review_stat.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product_review_stat.update_time
     *
     * @return the value of s_product_review_stat.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_product_review_stat.update_time
     *
     * @param updateTime the value for s_product_review_stat.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}