package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;

public class TConRole extends BaseEntity<String> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_ROLE.ROLE_NO
     *
     * @mbggenerated
     */
    private String roleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_ROLE.REMAKER
     *
     * @mbggenerated
     */
    private String remaker;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_ROLE.ROLE_NO
     *
     * @return the value of T_CON_ROLE.ROLE_NO
     *
     * @mbggenerated
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_ROLE.ROLE_NO
     *
     * @param roleNo the value for T_CON_ROLE.ROLE_NO
     *
     * @mbggenerated
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_ROLE.ROLE_NAME
     *
     * @return the value of T_CON_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_CON_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_ROLE.REMAKER
     *
     * @return the value of T_CON_ROLE.REMAKER
     *
     * @mbggenerated
     */
    public String getRemaker() {
        return remaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_ROLE.REMAKER
     *
     * @param remaker the value for T_CON_ROLE.REMAKER
     *
     * @mbggenerated
     */
    public void setRemaker(String remaker) {
        this.remaker = remaker;
    }

}