package com.tian.sakura.cdd.db.domain.product;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import com.tian.sakura.cdd.db.domain.productImg.ProductImg;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Data
public class Product extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     * 商品表主键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.id
     *
     * @mbg.generated
     */
    private String id;

    private String shopId;

    /**
     * Database Column Remarks:
     * 分类ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.type_id
     *
     * @mbg.generated
     */
    private String typeId;

    /**
     * Database Column Remarks:
     * 商品名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * Database Column Remarks:
     * 商品图片
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.product_img
     *
     * @mbg.generated
     */
    private String productImg;

    /**
     * Database Column Remarks:
     * 商品简介
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.product_des
     *
     * @mbg.generated
     */
    private String productDes;

    /**
     * Database Column Remarks:
     * 创建日期
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 创建人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     * Database Column Remarks:
     * 更新日期
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     * 更新人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;

    /**
     * Database Column Remarks:
     * 商品状态  0 未发布 1 已发布 未成交 2 已成交 3 已下架
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.product_status
     *
     * @mbg.generated
     */
    private Integer productStatus;

    /**
     * Database Column Remarks:
     * 总任务份数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.task_number
     *
     * @mbg.generated
     */
    private Integer taskNumber;

    /**
     * Database Column Remarks:
     * 商品价格（单位元）
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.product_price
     *
     * @mbg.generated
     */
    private BigDecimal productPrice;

    /**
     * Database Column Remarks:
     * 总佣金（单位元）
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.total_reward
     *
     * @mbg.generated
     */
    private BigDecimal totalReward;

    /**
     * Database Column Remarks:
     * 任务单价（单位元）
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.task_price
     *
     * @mbg.generated
     */
    private BigDecimal taskPrice;

    /**
     * Database Column Remarks:
     * 独赢奖励,买家立返
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.success_reward
     *
     * @mbg.generated
     */
    private String successReward;

    /**
     * Database Column Remarks:
     * 躺赢奖励，同组任务线平份的奖金
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.every_reward
     *
     * @mbg.generated
     */
    private String everyReward;

    /**
     * Database Column Remarks:
     * 产品类型 1 新手标 2 正常标
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.product_type
     *
     * @mbg.generated
     */
    private Integer productType;

    /**
     * Database Column Remarks:
     * 商品详情（html）
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_product.product_detail
     *
     * @mbg.generated
     */
    private String productDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_product.id
     *
     * @return the value of s_product.id
     * @mbg.generated
     */
    /**
     * 用户ID
     */
    private String  userId;

    /**
     * 是否已关注商品（1：已关注  0：未关注）
     */
    private transient Integer followStatus;

    /**
     * 购买上限
     */
    private transient Integer buyNumber;

    /**
     * 商品数量也是任务线总数
     */
    private Integer totalNumber;
    /**
     * 任务有效天数
     */
    private Integer validDays;

    private String productTag;

    /**
     * 商户名称
     */
    private String shopName;
    
    //配送方式
    private Integer deliveryType;
    
    //折扣率
	private BigDecimal discountRate;

	//上架时间
	private Date startDate;
	
	//二级分类id
	private String type2Id;
	
	//运费
	private BigDecimal expressFee;
	
	//划线价格
	private BigDecimal scribingPrice;
	
	//库存
	private Integer stockNumber;
   
	//删除标志
	private  Integer deleteFlag;

	private String priceUnit;

	private BigDecimal costPrice;

	private List<ProductImg> productImgList;

	private String homeProductImg;
}