package com.tian.sakura.cdd.db.dao.user;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.db.domain.user.UserLevel;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserLevelMapper extends AbstractSingleMapper<UserLevel, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_level
     *
     * @mbg.generated
     */
    int insert(UserLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_level
     *
     * @mbg.generated
     */
    int insertSelective(UserLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_level
     *
     * @mbg.generated
     */
    UserLevel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserLevel record);

    List<UserLevel> getUserLevelList(UserLevel userLevel);
}