package com.tian.sakura.cdd.db.domain.order;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Order extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     * 用户id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     * 支付方式  0 微信 1 支付宝 2 。。。
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order.payment_type
     *
     * @mbg.generated
     */
    private Integer paymentType;

    /**
     * Database Column Remarks:
     * 付款状态:0:未付款;1:已付款 2:已结算到冻结
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order.payment_state
     *
     * @mbg.generated
     */
    private Integer paymentState;

    /**
     * Database Column Remarks:
     * 支付(付款)时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order.payment_time
     *
     * @mbg.generated
     */
    private Date paymentTime;

    private Date createTime;

    /**
     * Database Column Remarks:
     * 实付金额
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order.pay_amount
     *
     * @mbg.generated
     */
    private BigDecimal payAmount;

    /**
     * Database Column Remarks:
     * 0-APP,1-微信公众号,2-小程序
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order.channel
     *
     * @mbg.generated
     */
    private Integer channel;

    //用户昵称
    private String nickName;

    //用户手机号
    private String userPhone;

}