package com.tian.sakura.cdd.db.dao.shopCatlog;

import java.util.List;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.db.domain.shopCatlog.ShopCatlog;

public interface ShopCatlogMapper extends AbstractSingleMapper<ShopCatlog,Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_shop_cat_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_shop_cat_rel
     *
     * @mbg.generated
     */
    int insert(ShopCatlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_shop_cat_rel
     *
     * @mbg.generated
     */
    int insertSelective(ShopCatlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_shop_cat_rel
     *
     * @mbg.generated
     */
    ShopCatlog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_shop_cat_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopCatlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_shop_cat_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopCatlog record);
    
    //查询店铺经营类目
    List<ShopCatlog> qryShopCatlog(Integer shopId);
}