package com.tian.sakura.cdd.db.domain.login;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_cust_auth_token
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CustAuthToken extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_auth_token.cust_no
     *
     * @mbg.generated
     */
    private String custNo;

    /**
     * Database Column Remarks:
     *   令牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_auth_token.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * Database Column Remarks:
     *   起始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_auth_token.start_time
     *
     * @mbg.generated
     */
    private Long startTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_auth_token.cust_id
     *
     * @return the value of t_cust_auth_token.cust_id
     *
     * @mbg.generated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_auth_token.cust_id
     *
     * @param custNo the value for t_cust_auth_token.cust_no
     *
     * @mbg.generated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_auth_token.token
     *
     * @return the value of t_cust_auth_token.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_auth_token.token
     *
     * @param token the value for t_cust_auth_token.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_auth_token.start_time
     *
     * @return the value of t_cust_auth_token.start_time
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_auth_token.start_time
     *
     * @param startTime the value for t_cust_auth_token.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

}