package com.tian.sakura.cdd.db.domain.login;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_account
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LoginAccount extends BaseEntity<Long> {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.LOGIN_NO
     *
     * @mbg.generated
     */
    private String loginNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.PASSWORD_SET_DATE
     *
     * @mbg.generated
     */
    private Date passwordSetDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.PASSWORD_EXPIRE_DATE
     *
     * @mbg.generated
     */
    private Date passwordExpireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.PASSWORD1
     *
     * @mbg.generated
     */
    private String password1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.PASSWORD2
     *
     * @mbg.generated
     */
    private String password2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.PASSWORD3
     *
     * @mbg.generated
     */
    private String password3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.PASSWORD4
     *
     * @mbg.generated
     */
    private String password4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.ACCOUNT_TYPE
     *
     * @mbg.generated
     */
    private String accountType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.LOGIN_NO
     *
     * @return the value of t_account.LOGIN_NO
     *
     * @mbg.generated
     */
    public String getLoginNo() {
        return loginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.LOGIN_NO
     *
     * @param loginNo the value for t_account.LOGIN_NO
     *
     * @mbg.generated
     */
    public void setLoginNo(String loginNo) {
        this.loginNo = loginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.PASSWORD
     *
     * @return the value of t_account.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.PASSWORD
     *
     * @param password the value for t_account.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.PASSWORD_SET_DATE
     *
     * @return the value of t_account.PASSWORD_SET_DATE
     *
     * @mbg.generated
     */
    public Date getPasswordSetDate() {
        return passwordSetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.PASSWORD_SET_DATE
     *
     * @param passwordSetDate the value for t_account.PASSWORD_SET_DATE
     *
     * @mbg.generated
     */
    public void setPasswordSetDate(Date passwordSetDate) {
        this.passwordSetDate = passwordSetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.PASSWORD_EXPIRE_DATE
     *
     * @return the value of t_account.PASSWORD_EXPIRE_DATE
     *
     * @mbg.generated
     */
    public Date getPasswordExpireDate() {
        return passwordExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.PASSWORD_EXPIRE_DATE
     *
     * @param passwordExpireDate the value for t_account.PASSWORD_EXPIRE_DATE
     *
     * @mbg.generated
     */
    public void setPasswordExpireDate(Date passwordExpireDate) {
        this.passwordExpireDate = passwordExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.PASSWORD1
     *
     * @return the value of t_account.PASSWORD1
     *
     * @mbg.generated
     */
    public String getPassword1() {
        return password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.PASSWORD1
     *
     * @param password1 the value for t_account.PASSWORD1
     *
     * @mbg.generated
     */
    public void setPassword1(String password1) {
        this.password1 = password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.PASSWORD2
     *
     * @return the value of t_account.PASSWORD2
     *
     * @mbg.generated
     */
    public String getPassword2() {
        return password2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.PASSWORD2
     *
     * @param password2 the value for t_account.PASSWORD2
     *
     * @mbg.generated
     */
    public void setPassword2(String password2) {
        this.password2 = password2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.PASSWORD3
     *
     * @return the value of t_account.PASSWORD3
     *
     * @mbg.generated
     */
    public String getPassword3() {
        return password3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.PASSWORD3
     *
     * @param password3 the value for t_account.PASSWORD3
     *
     * @mbg.generated
     */
    public void setPassword3(String password3) {
        this.password3 = password3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.PASSWORD4
     *
     * @return the value of t_account.PASSWORD4
     *
     * @mbg.generated
     */
    public String getPassword4() {
        return password4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.PASSWORD4
     *
     * @param password4 the value for t_account.PASSWORD4
     *
     * @mbg.generated
     */
    public void setPassword4(String password4) {
        this.password4 = password4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.ACCOUNT_TYPE
     *
     * @return the value of t_account.ACCOUNT_TYPE
     *
     * @mbg.generated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.ACCOUNT_TYPE
     *
     * @param accountType the value for t_account.ACCOUNT_TYPE
     *
     * @mbg.generated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
}