package com.tian.sakura.cdd.db.domain.shopCatlog;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_shop_cat_rel
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopCatlog extends BaseEntity<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_cat_rel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商铺id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_cat_rel.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * Database Column Remarks:
     *   商品一级分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop_cat_rel.product_type_id
     *
     * @mbg.generated
     */
    private Integer productTypeId;

    private String productTypeName;
    
    public String getProductTypeName() {
		return productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_cat_rel.id
     *
     * @return the value of s_shop_cat_rel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_cat_rel.id
     *
     * @param id the value for s_shop_cat_rel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_cat_rel.shop_id
     *
     * @return the value of s_shop_cat_rel.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_cat_rel.shop_id
     *
     * @param shopId the value for s_shop_cat_rel.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop_cat_rel.product_type_id
     *
     * @return the value of s_shop_cat_rel.product_type_id
     *
     * @mbg.generated
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop_cat_rel.product_type_id
     *
     * @param productTypeId the value for s_shop_cat_rel.product_type_id
     *
     * @mbg.generated
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }
}