package com.tian.sakura.cdd.db.dao.express;

import com.tian.sakura.cdd.common.entity.AbstractSingleMapper;
import com.tian.sakura.cdd.db.domain.express.Express;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ExpressMapper extends AbstractSingleMapper<Express, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_express
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_express
     *
     * @mbg.generated
     */
    int insert(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_express
     *
     * @mbg.generated
     */
    int insertSelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_express
     *
     * @mbg.generated
     */
    Express selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_express
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_express
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Express record);

    List<Express> queryExpressList(Express express);
}