package com.tian.sakura.cdd.db.domain.shop;

import java.util.Date;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_shop
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Shop extends BaseEntity<Integer> {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商铺编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_no
     *
     * @mbg.generated
     */
    private String shopNo;

    /**
     * Database Column Remarks:
     *   店铺logo
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_logo
     *
     * @mbg.generated
     */
    private String shopLogo;

    /**
     * Database Column Remarks:
     *   店铺名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     * Database Column Remarks:
     *   店铺星级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_star
     *
     * @mbg.generated
     */
    private Integer shopStar;

    /**
     * Database Column Remarks:
     *   店铺评价分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_score
     *
     * @mbg.generated
     */
    private Integer shopScore;

    /**
     * Database Column Remarks:
     *   售后服务分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_service
     *
     * @mbg.generated
     */
    private Integer shopService;

    /**
     * Database Column Remarks:
     *   店铺简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_desc
     *
     * @mbg.generated
     */
    private String shopDesc;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_province
     *
     * @mbg.generated
     */
    private String shopProvince;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_city
     *
     * @mbg.generated
     */
    private String shopCity;
    
    //区县
    private String shopCountry;

    public String getShopCountry() {
		return shopCountry;
	}

	public void setShopCountry(String shopCountry) {
		this.shopCountry = shopCountry;
	}

	/**
     * Database Column Remarks:
     *   所在地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_area
     *
     * @mbg.generated
     */
    private String shopArea;

    /**
     * Database Column Remarks:
     *   开店时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * Database Column Remarks:
     *   营业执照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.license
     *
     * @mbg.generated
     */
    private String license;

    /**
     * Database Column Remarks:
     *   法人代表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.legal_person
     *
     * @mbg.generated
     */
    private String legalPerson;

    /**
     * Database Column Remarks:
     *   联系手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   座机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.telphone
     *
     * @mbg.generated
     */
    private String telphone;

    /**
     * Database Column Remarks:
     *   0-个人  1-企业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.shop_type
     *
     * @mbg.generated
     */
    private Integer shopType;

    /**
     * Database Column Remarks:
     *   常用邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   客服电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.call_center
     *
     * @mbg.generated
     */
    private String callCenter;

    /**
     * Database Column Remarks:
     *   身份证正面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.front_id
     *
     * @mbg.generated
     */
    private String frontId;

    /**
     * Database Column Remarks:
     *   身份证背面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.back_id
     *
     * @mbg.generated
     */
    private String backId;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * Database Column Remarks:
     *   身份证有效截止日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.id_card_expire
     *
     * @mbg.generated
     */
    private String idCardExpire;

    /**
     * Database Column Remarks:
     *   企业名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.corp_name
     *
     * @mbg.generated
     */
    private String corpName;

    /**
     * Database Column Remarks:
     *   营业执照号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.license_no
     *
     * @mbg.generated
     */
    private String licenseNo;

    /**
     * Database Column Remarks:
     *   客服微信号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.weixin
     *
     * @mbg.generated
     */
    private String weixin;

    /**
     * Database Column Remarks:
     *   客服qq
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_shop.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    private String qrCode;
    
    public String getQrCode() {
		return qrCode;
	}

	public void setQrCode(String qrCode) {
		this.qrCode = qrCode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.id
     *
     * @return the value of s_shop.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.id
     *
     * @param id the value for s_shop.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_no
     *
     * @return the value of s_shop.shop_no
     *
     * @mbg.generated
     */
    public String getShopNo() {
        return shopNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_no
     *
     * @param shopNo the value for s_shop.shop_no
     *
     * @mbg.generated
     */
    public void setShopNo(String shopNo) {
        this.shopNo = shopNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_logo
     *
     * @return the value of s_shop.shop_logo
     *
     * @mbg.generated
     */
    public String getShopLogo() {
        return shopLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_logo
     *
     * @param shopLogo the value for s_shop.shop_logo
     *
     * @mbg.generated
     */
    public void setShopLogo(String shopLogo) {
        this.shopLogo = shopLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_name
     *
     * @return the value of s_shop.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_name
     *
     * @param shopName the value for s_shop.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_star
     *
     * @return the value of s_shop.shop_star
     *
     * @mbg.generated
     */
    public Integer getShopStar() {
        return shopStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_star
     *
     * @param shopStar the value for s_shop.shop_star
     *
     * @mbg.generated
     */
    public void setShopStar(Integer shopStar) {
        this.shopStar = shopStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_score
     *
     * @return the value of s_shop.shop_score
     *
     * @mbg.generated
     */
    public Integer getShopScore() {
        return shopScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_score
     *
     * @param shopScore the value for s_shop.shop_score
     *
     * @mbg.generated
     */
    public void setShopScore(Integer shopScore) {
        this.shopScore = shopScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_service
     *
     * @return the value of s_shop.shop_service
     *
     * @mbg.generated
     */
    public Integer getShopService() {
        return shopService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_service
     *
     * @param shopService the value for s_shop.shop_service
     *
     * @mbg.generated
     */
    public void setShopService(Integer shopService) {
        this.shopService = shopService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_desc
     *
     * @return the value of s_shop.shop_desc
     *
     * @mbg.generated
     */
    public String getShopDesc() {
        return shopDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_desc
     *
     * @param shopDesc the value for s_shop.shop_desc
     *
     * @mbg.generated
     */
    public void setShopDesc(String shopDesc) {
        this.shopDesc = shopDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_province
     *
     * @return the value of s_shop.shop_province
     *
     * @mbg.generated
     */
    public String getShopProvince() {
        return shopProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_province
     *
     * @param shopProvince the value for s_shop.shop_province
     *
     * @mbg.generated
     */
    public void setShopProvince(String shopProvince) {
        this.shopProvince = shopProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_city
     *
     * @return the value of s_shop.shop_city
     *
     * @mbg.generated
     */
    public String getShopCity() {
        return shopCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_city
     *
     * @param shopCity the value for s_shop.shop_city
     *
     * @mbg.generated
     */
    public void setShopCity(String shopCity) {
        this.shopCity = shopCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_area
     *
     * @return the value of s_shop.shop_area
     *
     * @mbg.generated
     */
    public String getShopArea() {
        return shopArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_area
     *
     * @param shopArea the value for s_shop.shop_area
     *
     * @mbg.generated
     */
    public void setShopArea(String shopArea) {
        this.shopArea = shopArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.start_date
     *
     * @return the value of s_shop.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.start_date
     *
     * @param startDate the value for s_shop.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.license
     *
     * @return the value of s_shop.license
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.license
     *
     * @param license the value for s_shop.license
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.legal_person
     *
     * @return the value of s_shop.legal_person
     *
     * @mbg.generated
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.legal_person
     *
     * @param legalPerson the value for s_shop.legal_person
     *
     * @mbg.generated
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.mobile
     *
     * @return the value of s_shop.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.mobile
     *
     * @param mobile the value for s_shop.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.telphone
     *
     * @return the value of s_shop.telphone
     *
     * @mbg.generated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.telphone
     *
     * @param telphone the value for s_shop.telphone
     *
     * @mbg.generated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.shop_type
     *
     * @return the value of s_shop.shop_type
     *
     * @mbg.generated
     */
    public Integer getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.shop_type
     *
     * @param shopType the value for s_shop.shop_type
     *
     * @mbg.generated
     */
    public void setShopType(Integer shopType) {
        this.shopType = shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.email
     *
     * @return the value of s_shop.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.email
     *
     * @param email the value for s_shop.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.call_center
     *
     * @return the value of s_shop.call_center
     *
     * @mbg.generated
     */
    public String getCallCenter() {
        return callCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.call_center
     *
     * @param callCenter the value for s_shop.call_center
     *
     * @mbg.generated
     */
    public void setCallCenter(String callCenter) {
        this.callCenter = callCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.front_id
     *
     * @return the value of s_shop.front_id
     *
     * @mbg.generated
     */
    public String getFrontId() {
        return frontId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.front_id
     *
     * @param frontId the value for s_shop.front_id
     *
     * @mbg.generated
     */
    public void setFrontId(String frontId) {
        this.frontId = frontId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.back_id
     *
     * @return the value of s_shop.back_id
     *
     * @mbg.generated
     */
    public String getBackId() {
        return backId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.back_id
     *
     * @param backId the value for s_shop.back_id
     *
     * @mbg.generated
     */
    public void setBackId(String backId) {
        this.backId = backId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.id_card
     *
     * @return the value of s_shop.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.id_card
     *
     * @param idCard the value for s_shop.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.id_card_expire
     *
     * @return the value of s_shop.id_card_expire
     *
     * @mbg.generated
     */
    public String getIdCardExpire() {
        return idCardExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.id_card_expire
     *
     * @param idCardExpire the value for s_shop.id_card_expire
     *
     * @mbg.generated
     */
    public void setIdCardExpire(String idCardExpire) {
        this.idCardExpire = idCardExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.corp_name
     *
     * @return the value of s_shop.corp_name
     *
     * @mbg.generated
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.corp_name
     *
     * @param corpName the value for s_shop.corp_name
     *
     * @mbg.generated
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.license_no
     *
     * @return the value of s_shop.license_no
     *
     * @mbg.generated
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.license_no
     *
     * @param licenseNo the value for s_shop.license_no
     *
     * @mbg.generated
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.weixin
     *
     * @return the value of s_shop.weixin
     *
     * @mbg.generated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.weixin
     *
     * @param weixin the value for s_shop.weixin
     *
     * @mbg.generated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.qq
     *
     * @return the value of s_shop.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.qq
     *
     * @param qq the value for s_shop.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_shop.create_time
     *
     * @return the value of s_shop.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_shop.create_time
     *
     * @param createTime the value for s_shop.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public Integer provinceId;
    public Integer cityId;
    public Integer countryId;

	public Integer getCountryId() {
		return countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public Integer getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}
    
}