package com.tian.sakura.cdd.db.domain.user;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_withdraw
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserWithdraw extends BaseEntity<String> {

    /**
     * Database Column Remarks:
     *   提现人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   银行名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.bank_name
     *
     * @mbg.generated
     */
    private String bankName;

    /**
     * Database Column Remarks:
     *   银行编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.bank_code
     *
     * @mbg.generated
     */
    private String bankCode;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * Database Column Remarks:
     *   身份证号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * Database Column Remarks:
     *   银行卡号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.card_num
     *
     * @mbg.generated
     */
    private String cardNum;

    /**
     * Database Column Remarks:
     *   提现金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   状态 0 已申请 1 已打款 2 已驳回
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.status
     *
     * @mbg.generated
     */
    private Integer withdrawStatus;

    /**
     * Database Column Remarks:
     *   打款sn
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.pay_sn
     *
     * @mbg.generated
     */
    private String paySn;

    /**
     * Database Column Remarks:
     *   处理人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.deal_user
     *
     * @mbg.generated
     */
    private Integer dealUser;

    /**
     * Database Column Remarks:
     *   处理时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.deal_time
     *
     * @mbg.generated
     */
    private Date dealTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   申请日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_withdraw.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.user_id
     *
     * @return the value of s_user_withdraw.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.user_id
     *
     * @param userId the value for s_user_withdraw.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.bank_name
     *
     * @return the value of s_user_withdraw.bank_name
     *
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.bank_name
     *
     * @param bankName the value for s_user_withdraw.bank_name
     *
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.bank_code
     *
     * @return the value of s_user_withdraw.bank_code
     *
     * @mbg.generated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.bank_code
     *
     * @param bankCode the value for s_user_withdraw.bank_code
     *
     * @mbg.generated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.real_name
     *
     * @return the value of s_user_withdraw.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.real_name
     *
     * @param realName the value for s_user_withdraw.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.id_card
     *
     * @return the value of s_user_withdraw.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.id_card
     *
     * @param idCard the value for s_user_withdraw.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.card_num
     *
     * @return the value of s_user_withdraw.card_num
     *
     * @mbg.generated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.card_num
     *
     * @param cardNum the value for s_user_withdraw.card_num
     *
     * @mbg.generated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.amount
     *
     * @return the value of s_user_withdraw.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.amount
     *
     * @param amount the value for s_user_withdraw.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }


    public Integer getWithdrawStatus() {
        return withdrawStatus;
    }

    public void setWithdrawStatus(Integer withdrawStatus) {
        this.withdrawStatus = withdrawStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.pay_sn
     *
     * @return the value of s_user_withdraw.pay_sn
     *
     * @mbg.generated
     */
    public String getPaySn() {
        return paySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.pay_sn
     *
     * @param paySn the value for s_user_withdraw.pay_sn
     *
     * @mbg.generated
     */
    public void setPaySn(String paySn) {
        this.paySn = paySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.deal_user
     *
     * @return the value of s_user_withdraw.deal_user
     *
     * @mbg.generated
     */
    public Integer getDealUser() {
        return dealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.deal_user
     *
     * @param dealUser the value for s_user_withdraw.deal_user
     *
     * @mbg.generated
     */
    public void setDealUser(Integer dealUser) {
        this.dealUser = dealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.deal_time
     *
     * @return the value of s_user_withdraw.deal_time
     *
     * @mbg.generated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.deal_time
     *
     * @param dealTime the value for s_user_withdraw.deal_time
     *
     * @mbg.generated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.remark
     *
     * @return the value of s_user_withdraw.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.remark
     *
     * @param remark the value for s_user_withdraw.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_withdraw.create_time
     *
     * @return the value of s_user_withdraw.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_withdraw.create_time
     *
     * @param createTime the value for s_user_withdraw.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}