package com.tian.sakura.cdd.db.domain.auth;

import com.tian.sakura.cdd.common.entity.BaseEntity;

public class TConPermResource extends BaseEntity<String> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_PERM_RESOURCE.PERMISSION_ID
     *
     * @mbggenerated
     */
    private String permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CON_PERM_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_PERM_RESOURCE.PERMISSION_ID
     *
     * @return the value of T_CON_PERM_RESOURCE.PERMISSION_ID
     *
     * @mbggenerated
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_PERM_RESOURCE.PERMISSION_ID
     *
     * @param permissionId the value for T_CON_PERM_RESOURCE.PERMISSION_ID
     *
     * @mbggenerated
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CON_PERM_RESOURCE.RESOURCE_ID
     *
     * @return the value of T_CON_PERM_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CON_PERM_RESOURCE.RESOURCE_ID
     *
     * @param resourceId the value for T_CON_PERM_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

}