package com.tian.sakura.cdd.db.domain.taskLine;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_task_line
 *
 * @mbg.generated do_not_delete_during_merge
 */
@EqualsAndHashCode(callSuper = true)
@Data
public class TaskLine  extends BaseEntity<String>{
    /**
     * Database Column Remarks:
     *   索引ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   该条任务线总任务数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.total_task
     *
     * @mbg.generated
     */
    private Integer totalTask;

    /**
     * Database Column Remarks:
     *   该条任务线已领取的任务数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.received_task
     *
     * @mbg.generated
     */
    private Integer receivedTask;

    /**
     * Database Column Remarks:
     *   0-未满 1-已满 2-已分润
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.line_status
     *
     * @mbg.generated
     */
    private Integer lineStatus;

    /**
     * 结算状态
     */
    private Integer settleStatus;

    /**
     * Database Column Remarks:
     *   每个商品各任务线顺序（1、2、3......）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.line_order
     *
     * @mbg.generated
     */
    private Integer lineOrder;

    private String orderProductId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_task_line.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;
}