package com.tian.sakura.cdd.db.domain.activity;

import com.tian.sakura.cdd.common.entity.BaseEntity;
import com.tian.sakura.cdd.db.domain.product.Product;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_activity_product
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class ActivityProduct extends BaseEntity<String> {
    /**
     * Database Column Remarks:
     * 活动商品主键ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     * 活动id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.act_id
     *
     * @mbg.generated
     */
    private String actId;

    /**
     * Database Column Remarks:
     * 商品id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     * 任务金促销价
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     * 商品划线价格
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.scribing_price
     *
     * @mbg.generated
     */
    private BigDecimal scribingPrice;

    /**
     * Database Column Remarks:
     * 开始时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * Database Column Remarks:
     * 结束时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     * Database Column Remarks:
     * 显示顺序
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.s_order
     *
     * @mbg.generated
     */
    private Integer sOrder;

    /**
     * Database Column Remarks:
     * 创建日期
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 更新日期
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     * 创建者
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     * Database Column Remarks:
     * 更新者
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_activity_product.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;

    private List<Product> productList;
}