package com.tian.sakura.cdd.db.domain.userTaskLine;

import com.tian.sakura.cdd.common.entity.BaseEntity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_user_task_line
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserTaskLine extends BaseEntity<String> {

    private String userId;
    private String taskId;
    private String productId;
    private String taskLineId;
    private Integer payStatus;
    private BigDecimal payAmount;
    private Date payTime;
    private Integer lineStatus;
    //冗余字段
    private Integer lineOrder;

    private Integer sumCount;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_task_line.user_id
     *
     * @return the value of s_user_task_line.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_task_line.user_id
     *
     * @param userId the value for s_user_task_line.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_task_line.task_id
     *
     * @return the value of s_user_task_line.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_task_line.task_id
     *
     * @param taskId the value for s_user_task_line.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_task_line.product_id
     *
     * @return the value of s_user_task_line.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_task_line.product_id
     *
     * @param productId the value for s_user_task_line.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_task_line.task_line_id
     *
     * @return the value of s_user_task_line.task_line_id
     *
     * @mbg.generated
     */
    public String getTaskLineId() {
        return taskLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_task_line.task_line_id
     *
     * @param taskLineId the value for s_user_task_line.task_line_id
     *
     * @mbg.generated
     */
    public void setTaskLineId(String taskLineId) {
        this.taskLineId = taskLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_task_line.pay_status
     *
     * @return the value of s_user_task_line.pay_status
     *
     * @mbg.generated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_task_line.pay_status
     *
     * @param payStatus the value for s_user_task_line.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_task_line.pay_amount
     *
     * @return the value of s_user_task_line.pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_task_line.pay_amount
     *
     * @param payAmount the value for s_user_task_line.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_task_line.pay_time
     *
     * @return the value of s_user_task_line.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_task_line.pay_time
     *
     * @param payTime the value for s_user_task_line.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    public Integer getLineStatus() {
        return lineStatus;
    }

    public void setLineStatus(Integer lineStatus) {
        this.lineStatus = lineStatus;
    }

    public Integer getLineOrder() {
        return lineOrder;
    }

    public void setLineOrder(Integer lineOrder) {
        this.lineOrder = lineOrder;
    }

    public Integer getSumCount() {
        return sumCount;
    }

    public void setSumCount(Integer sumCount) {
        this.sumCount = sumCount;
    }
}