package com.tian.sakura.cdd.db.domain.base;


import java.awt.image.RGBImageFilter;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_jpush_reg
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class JpushRegKey {
    /**
     * Database Column Remarks:
     *   设备id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_jpush_reg.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     * Database Column Remarks:
     *   极光推送的设备注册id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_jpush_reg.registration_id
     *
     * @mbg.generated
     */
    private String registrationId;

    public JpushRegKey() {

    }

    public JpushRegKey(String deviceId, String registrationId) {
        this.deviceId = deviceId;
        this.registrationId = registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_jpush_reg.device_id
     *
     * @return the value of s_jpush_reg.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_jpush_reg.device_id
     *
     * @param deviceId the value for s_jpush_reg.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_jpush_reg.registration_id
     *
     * @return the value of s_jpush_reg.registration_id
     *
     * @mbg.generated
     */
    public String getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_jpush_reg.registration_id
     *
     * @param registrationId the value for s_jpush_reg.registration_id
     *
     * @mbg.generated
     */
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
}