package com.tian.sakura.cdd.db.domain.base;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_bank
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Bank extends BaseEntity<Integer> {

    /**
     * Database Column Remarks:
     *   银行名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_bank.bank_name
     *
     * @mbg.generated
     */
    private String bankName;

    /**
     * Database Column Remarks:
     *   银行编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_bank.bank_code
     *
     * @mbg.generated
     */
    private String bankCode;

    /**
     * Database Column Remarks:
     *   银行图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_bank.bank_icon
     *
     * @mbg.generated
     */
    private String bankIcon;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bank.bank_name
     *
     * @return the value of s_bank.bank_name
     *
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bank.bank_name
     *
     * @param bankName the value for s_bank.bank_name
     *
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bank.bank_code
     *
     * @return the value of s_bank.bank_code
     *
     * @mbg.generated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bank.bank_code
     *
     * @param bankCode the value for s_bank.bank_code
     *
     * @mbg.generated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bank.bank_icon
     *
     * @return the value of s_bank.bank_icon
     *
     * @mbg.generated
     */
    public String getBankIcon() {
        return bankIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bank.bank_icon
     *
     * @param bankIcon the value for s_bank.bank_icon
     *
     * @mbg.generated
     */
    public void setBankIcon(String bankIcon) {
        this.bankIcon = bankIcon;
    }
}