package com.tian.sakura.cdd.db.domain.base;

import com.tian.sakura.cdd.common.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table s_func_module
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FuncModule extends BaseEntity<String> {

    /**
     * Database Column Remarks:
     *   功能模块名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_func_module.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     * Database Column Remarks:
     *   图标url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_func_module.module_url
     *
     * @mbg.generated
     */
    private String moduleUrl;

    /**
     * Database Column Remarks:
     *   显示顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_func_module.s_order
     *
     * @mbg.generated
     */
    private Integer sOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_func_module.jump_url
     *
     * @mbg.generated
     */
    private String jumpUrl;

    /**
     * Database Column Remarks:
     *   状态 0-创建 1-发布 2-下架 3-删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_func_module.module_status
     *
     * @mbg.generated
     */
    private Integer moduleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_func_module.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_func_module.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_func_module.module_name
     *
     * @return the value of s_func_module.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_func_module.module_name
     *
     * @param moduleName the value for s_func_module.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_func_module.module_url
     *
     * @return the value of s_func_module.module_url
     *
     * @mbg.generated
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_func_module.module_url
     *
     * @param moduleUrl the value for s_func_module.module_url
     *
     * @mbg.generated
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_func_module.s_order
     *
     * @return the value of s_func_module.s_order
     *
     * @mbg.generated
     */
    public Integer getsOrder() {
        return sOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_func_module.s_order
     *
     * @param sOrder the value for s_func_module.s_order
     *
     * @mbg.generated
     */
    public void setsOrder(Integer sOrder) {
        this.sOrder = sOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_func_module.jump_url
     *
     * @return the value of s_func_module.jump_url
     *
     * @mbg.generated
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_func_module.jump_url
     *
     * @param jumpUrl the value for s_func_module.jump_url
     *
     * @mbg.generated
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_func_module.module_status
     *
     * @return the value of s_func_module.module_status
     *
     * @mbg.generated
     */
    public Integer getModuleStatus() {
        return moduleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_func_module.module_status
     *
     * @param moduleStatus the value for s_func_module.module_status
     *
     * @mbg.generated
     */
    public void setModuleStatus(Integer moduleStatus) {
        this.moduleStatus = moduleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_func_module.create_user
     *
     * @return the value of s_func_module.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_func_module.create_user
     *
     * @param createUser the value for s_func_module.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_func_module.update_user
     *
     * @return the value of s_func_module.update_user
     *
     * @mbg.generated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_func_module.update_user
     *
     * @param updateUser the value for s_func_module.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}